version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: internal-mgmt-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Admin@123
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - JWT_SECRET=92bd9d6842e5e4a52e4744fc9cbe79c7a55fc770e68cabe36ba7c7eb5a2ae0dfa2594c59ea2a85a64fb99e3f73a2167d5ed2fdb51a8c58cbace93a3f9c0ec3e9
    volumes:
      - app-uploads:/app/uploads
      - app-logs:/app/logs
    depends_on:
      - mysql
    networks:
      - internal-mgmt-network

  mysql:
    image: mysql:8.0
    container_name: internal-mgmt-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=dev_sdims
      - MYSQL_ROOT_PASSWORD=Admin@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/init_tables.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - internal-mgmt-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  app-uploads:
  app-logs:
  mysql-data:

networks:
  internal-mgmt-network:
    driver: bridge 