# Sample Spring Boot application config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_sdims?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: Admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations: classpath:init_tables.sql
      mode: always
      continue-on-error: true
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080
  servlet:
    context-path: /

app:
  cors:
    # Allowed origins for CORS (comma-separated list if multiple)
    allowed-origins: http://localhost:3000
    # Allow credentials
    allow-credentials: true
    # Allowed methods
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    # Allowed headers
    allowed-headers: authorization,content-type,x-auth-token
    # Exposed headers
    exposed-headers: x-auth-token
  jwt:
    # JWT Secret key - được sử dụng để ký JWT token (Nên được mã hóa/bảo vệ trong môi trường production)
    secret: 92bd9d6842e5e4a52e4744fc9cbe79c7a55fc770e68cabe36ba7c7eb5a2ae0dfa2594c59ea2a85a64fb99e3f73a2167d5ed2fdb51a8c58cbace93a3f9c0ec3e9
    # Thời gian sống của token (1 giờ)
    expirationMs: 3600000
    # Thời gian sống của refresh token (7 ngày)
    refreshExpirationMs: 604800000

logging:
  level:
    org.springframework.security: INFO
    com.company.internalmgmt: INFO
    com.company.internalmgmt.common.exception: DEBUG
    com.company.internalmgmt.modules.hrm: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30 